#!/bin/sh
# Rebuilds the generated data files from the research JSON. Run from this folder:  sh build-classics.sh
#   classics.js  <- classics-*.json + contest-*.json   (window.MYWAR_CLASSICS)
#   skaters.js   <- skaters-*.json                     (window.MYWAR_SKATERS)
cd "$(dirname "$0")"
bundle() {  # bundle <out.js> <global> <glob...>
  out=$1; global=$2; shift 2
  {
    echo "// Generated by build-classics.sh from $* — edit those files, not this one."
    echo "window.$global = [].concat("
    first=1
    for f in "$@"; do
      [ -f "$f" ] || continue
      [ $first -eq 1 ] || echo ","
      first=0
      cat "$f"
    done
    [ $first -eq 1 ] && echo "[]"
    echo ");"
  } > "$out"
  echo "$out rebuilt from: $(ls "$@" 2>/dev/null | tr '\n' ' ')"
}
bundle classics.js MYWAR_CLASSICS classics-*.json contest-*.json
bundle skaters.js MYWAR_SKATERS skaters-*.json
