#!/bin/sh
# Downloads each skater's portrait (from skaters-*.json) into portraits/ and writes portraits.js,
# which maps skater id -> local file so the page doesn't hotlink Wikimedia on every load.
# Re-runnable; already-downloaded files are kept. Run from this folder:  sh fetch-portraits.sh
cd "$(dirname "$0")"
mkdir -p portraits
UA='StompingGrounds/1.0 (local fan project; portrait cache)'
: > portraits.tmp
for f in skaters-*.json; do
  # one "name<TAB>photo" line per skater; the id is derived the same way app.js does it (nickname stripped, slugged)
  grep -o '"name": *"[^"]*"\|"photo": *"[^"]*"\|"photo": *null' "$f" | sed 's/^"[a-z]*": *//; s/^"//; s/"$//' | paste - - |
  while IFS="$(printf '\t')" read -r name url; do
    [ "$url" = "null" ] && continue
    # accents are dropped (Aurélien -> aurelien) to match app.js slug(); TRANSLIT leaves stray quote marks, so strip those
    id=$(printf '%s' "$name" | sed 's/ *\\"[^"]*\\" */ /g; s/ *"[^"]*" */ /g' | sed "s/'/-/g" | iconv -f utf-8 -t ascii//TRANSLIT 2>/dev/null | tr -d "'\"\`^~" | tr 'A-Z' 'a-z' | sed 's/[^a-z0-9]\{1,\}/-/g; s/^-//; s/-$//')
    ext=$(printf '%s' "$url" | sed 's/.*\.//' | tr 'A-Z' 'a-z'); [ "$ext" = "jpeg" ] && ext=jpg
    out="portraits/$id.$ext"
    if [ ! -s "$out" ]; then
      curl -sL --max-time 40 -A "$UA" -o "$out" "$url" || true
      sleep 2
    fi
    if [ -s "$out" ] && file "$out" | grep -qi 'image'; then
      printf '  "%s": "%s"\n' "$id" "$out" >> portraits.tmp
    else
      rm -f "$out"; echo "FAILED: $name ($url)"
    fi
  done
done
# Any image dropped into portraits/ by hand counts too, as long as it is named after the skater:
# lower case, spaces as dashes, no accents or nicknames — e.g. portraits/tom-penny.jpg.
# These win over a downloaded file, so you can override any portrait by dropping one in.
for img in portraits/*.jpg portraits/*.jpeg portraits/*.png portraits/*.webp portraits/*.gif; do
  [ -f "$img" ] || continue
  base=$(basename "$img"); id=${base%.*}
  grep -q "\"$id\":" portraits.tmp 2>/dev/null && continue
  printf '  "%s": "%s"\n' "$id" "$img" >> portraits.tmp
done

{
  printf '// Generated by fetch-portraits.sh — local portraits: downloads from skaters-*.json plus anything\n// you dropped into portraits/ yourself (named <first-last>.jpg). Re-run the script after adding files.\nwindow.MYWAR_PORTRAITS = {\n'
  paste -sd ',' portraits.tmp | sed 's/,/,\n/g'
  printf '};\n'
} > portraits.js
rm -f portraits.tmp
echo "portraits: $(ls portraits | wc -l) files, $(grep -c '^  "' portraits.js) mapped"
